CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	AbortPkt.$O AddBuffe.$O AddDosEn.$O AddPart.$O AddSegme.$O \
	AllocDos.$O AllDosTL.$O AssignAd.$O AssignLa.$O AssignLo.$O AssignPa.$O \
	AttemptL.$O ChangeMo.$O CheckSig.$O Cli.$O  \
	CliInit.$O CliInitN.$O CliInitR.$O Close.$O CompareD.$O  \
	CreateDi.$O CreateNe.$O CreaNPTL.$O CreatePr.$O CurrentD.$O DateStam.$O \
	DateToSt.$O Delay.$O DeleteFi.$O DeleteVa.$O DevicePr.$O  \
	DoPkt.$O DoPkt0.$O DoPkt1.$O DoPkt2.$O DoPkt3.$O DoPkt4.$O \
	DupLock.$O DupLockF.$O EndNotif.$O ErrorRep.$O  \
	ExAll.$O ExNext.$O Examine.$O ExamineF.$O Execute.$O  \
	Exit.$O FGetC.$O FGets.$O FPutC.$O FPuts.$O  \
	FRead.$O FWrite.$O FWritef.$O Fault.$O FilePart.$O FindArg.$O  \
	FindCliP.$O FindDosE.$O FindSegm.$O FindVar.$O Flush.$O  \
	Format.$O FPrintf.$O FreeArgs.$O FreeDevi.$O FreeDosE.$O FreeDosO.$O  \
	GetArgSt.$O GetConso.$O GetCurre.$O GetDevic.$O GetFileS.$O  \
	GetProg1.$O GetProgr.$O GetPromp.$O GetVar.$O Info.$O  \
	Inhibit.$O Input.$O Interna1.$O Internal.$O IoErr.$O  \
	IsFileSy.$O IsIntera.$O LoadSeg.$O Lock.$O LockDosL.$O  \
	LockRec1.$O LockReco.$O MakeDosE.$O MakeLink.$O MatchEnd.$O  \
	MatchFir.$O MatchNex.$O MatchPat.$O MatPatNC.$O MaxCli.$O NameFro1.$O \
	NameFrom.$O NewLoadS.$O NewLSTL.$O NextDosE.$O Open.$O  \
	OpenFrom.$O Output.$O ParentDi.$O ParentOf.$O ParPatNC.$O ParsePat.$O  \
	PathPart.$O Printf.$O PrintFau.$O PutStr.$O Read.$O ReadArgs.$O  \
	ReadItem.$O ReadLink.$O Relabel.$O RemAssig.$O RemDosEn.$O  \
	RemSegme.$O Rename.$O ReplyPkt.$O RunComma.$O SameDev.$O  \
	SameLock.$O Seek.$O SelectIn.$O SelectOu.$O SendPkt.$O  \
	SetArgSt.$O SetComme.$O SetConso.$O SetCurre.$O SetFile1.$O  \
	SetFileD.$O SetFileS.$O SetIoErr.$O SetMode.$O SetProg1.$O  \
	SetProgr.$O SetPromp.$O SetProte.$O SetVBuf.$O SetVar.$O  \
	SplitNam.$O StartNot.$O StrToDat.$O StrToLon.$O System.$O  SystemTL.$O \
	UnGetC.$O UnLoadSe.$O UnLock.$O UnLockDo.$O UnLockR1.$O  \
	UnLockRe.$O VFPrintf.$O VFWritef.$O VPrintf.$O WaitForC.$O  \
	WaitPkt.$O Write.$O WriteCha.$O

clib:	$(CLIB)

