#pragma amicall(DiskfontBase, 0x1e, OpenDiskFont(a0))
#pragma amicall(DiskfontBase, 0x24, AvailFonts(a0,d0,d1))
#pragma amicall(DiskfontBase, 0x2a, NewFontContents(a0,a1))
#pragma amicall(DiskfontBase, 0x30, DisposeFontContents(a1))
#pragma amicall(DiskfontBase, 0x36, NewScaledDiskFont(a0,a1))
