CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	AddFreeL.$O BumpRevi.$O DelDskOb.$O FindTool.$O FreeDisk.$O  \
	FreeFree.$O GetDefDi.$O GetDisk1.$O GetDiskO.$O GetIcon.$O  \
	MatchToo.$O PutDefDi.$O PutDiskO.$O PutIcon.$O

clib:	$(CLIB)

