CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	CreateCo.$O CreateGa.$O CreatGa1.$O CreateMe.$O CreatMe1.$O \
	DrawBeve.$O DrawBev1.$O FreeGadg.$O  \
	FreeMenu.$O FreeVisu.$O \
	GT_Begin.$O GT_EndRe.$O  \
	GT_Filte.$O GT_GetIM.$O GT_PostF.$O GT_Refre.$O GT_Reply.$O  \
	GT_SetGa.$O GT_SetG1.$O GetVisua.$O GetVis1.$O LayoutM1.$O \
	LayoutMe.$O LayoutM2.$O LayoutM3.$O

clib:	$(CLIB)

