CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	AddAppIc.$O AddAppMe.$O AddAppWi.$O RemoveA1.$O RemoveA2.$O\
	AddAppI.$O  AddAppM.$O  AddAppW.$O  \
	RemoveAp.$O 

clib:	$(CLIB)

