CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	AbortIO.$O AddDevic.$O AddHead.$O AddIntSe.$O AddLibra.$O  \
	AddMemLi.$O AddPort.$O AddResou.$O AddSemap.$O AddTail.$O  \
	AddTask.$O Alert.$O AllocAbs.$O AllocEnt.$O AllocMem.$O  \
	AllocPoo.$O AllocSig.$O AllocTra.$O AllocVec.$O Allocate.$O AttSemSh.$O \
	AttemptS.$O AvailMem.$O CacheCl1.$O CacheCle.$O CacheCon.$O  \
	CachePre.$O CachePos.$O  \
	Cause.$O CheckIO.$O ChildFre.$O ChildOrp.$O ChildSta.$O  \
	ChildWai.$O CloseDev.$O CloseLib.$O ColdRebo.$O CopyMem.$O  \
	CopyMemQ.$O CreateIO.$O CreateMs.$O CreatePr.$O Dealloca.$O  \
	Debug.$O DeleteIO.$O DeleteMs.$O DeletePr.$O Disable.$O  \
	DoIO.$O Enable.$O Enqueue.$O \
	FindName.$O FindPort.$O FindResi.$O FindSema.$O FindTask.$O  \
	Forbid.$O FreeEntr.$O FreeMem.$O FreePool.$O FreeSign.$O  \
	FreeTrap.$O FreeVec.$O GetCC.$O GetMsg.$O InitCode.$O  \
	InitResi.$O InitSema.$O InitStru.$O Insert.$O MakeFunc.$O  \
	MakeLibr.$O ObtainS1.$O ObtainS2.$O ObtainSe.$O OldOpenL.$O  \
	OpenDevi.$O OpenLibr.$O OpenReso.$O Permit.$O Procure.$O  \
	PutMsg.$O RawDoFmt.$O \
	Release1.$O ReleaseS.$O RemDevic.$O RemHead.$O RemIntSe.$O  \
	RemLibra.$O RemPort.$O RemResou.$O RemSemap.$O RemTail.$O  \
	RemTask.$O Remove.$O ReplyMsg.$O \
	SendIO.$O SetExcep.$O SetFunct.$O SetIntVe.$O  \
	SetSR.$O SetSigna.$O SetTaskP.$O Signal.$O StackSwa.$O  \
	SumKickD.$O SumLibra.$O SuperSta.$O Supervis.$O \
	TypeOfMe.$O UserStat.$O Vacate.$O Wait.$O WaitIO.$O \
	WaitPort.$O

clib:	$(CLIB)

