#include	<clib/alib_protos.h>
#include	<clib/asl_protos.h>
#include	<clib/battclock_protos.h>
#include	<clib/battmem_protos.h>
#include	<clib/cia_protos.h>
#include	<clib/commodities_protos.h>
#include	<clib/console_protos.h>
#include	<clib/diskfont_protos.h>
#include	<clib/dos_protos.h>
#include	<clib/exec_protos.h>
#include	<clib/expansion_protos.h>
#include	<clib/gadtools_protos.h>
#include	<clib/graphics_protos.h>
#include	<clib/icon_protos.h>
#include	<clib/iffparse_protos.h>
#include	<clib/input_protos.h>
#include	<clib/intuition_protos.h>
#include	<clib/keymap_protos.h>
#include	<clib/layers_protos.h>
#include	<clib/macros.h>
#include	<clib/misc_protos.h>
#include	<clib/potgo_protos.h>
#include	<clib/ramdrive_protos.h>
#include	<clib/timer_protos.h>
#include	<clib/translator_protos.h>
#include	<clib/utility_protos.h>
#include	<clib/wb_protos.h>

#ifndef __NO_PRAGMAS
#include	<pragmas/asl_lib.h>
#include	<pragmas/battclock_lib.h>
#include	<pragmas/battmem_lib.h>
#include	<pragmas/commodities_lib.h>
#include	<pragmas/console_lib.h>
#include	<pragmas/diskfont_lib.h>
#include	<pragmas/dos_lib.h>
#include	<pragmas/exec_lib.h>
#include	<pragmas/expansion_lib.h>
#include	<pragmas/gadtools_lib.h>
#include	<pragmas/graphics_lib.h>
#include	<pragmas/icon_lib.h>
#include	<pragmas/iffparse_lib.h>
#include	<pragmas/input_lib.h>
#include	<pragmas/misc_lib.h>
#include	<pragmas/intuition_lib.h>
#include	<pragmas/keymap_lib.h>
#include	<pragmas/layers_lib.h>
#include	<pragmas/potgo_lib.h>
#include	<pragmas/ramdrive_lib.h>
#include	<pragmas/timer_lib.h>
#include	<pragmas/translator_lib.h>
#include	<pragmas/utility_lib.h>
#include	<pragmas/wb_lib.h>
#endif

