CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	Activate.$O AddIEven.$O AttachCx.$O ClearCxO.$O \
	CreateCx.$O CxBroker.$O CxMsgDat.$O CxMsgID.$O \
	CxMsgTyp.$O CxObjErr.$O CxObjTyp.$O DeleteC1.$O DeleteCx.$O \
	DisposeC.$O DivertCx.$O EnqueueC.$O \
	InsertCx.$O InvertKe.$O ParseIX.$O RemoveCx.$O RouteCxM.$O \
	SetCxObj.$O SetFilt1.$O SetFilte.$O SetTrans.$O 

clib:	$(CLIB)

