CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	Activat1.$O Activate.$O AddClass.$O AddGList.$O AddGadge.$O  \
	AllocRem.$O AlohaWor.$O AutoRequ.$O BeginRef.$O BuildEas.$O BldEasy.$O \
	BuildSys.$O ChangeWi.$O ClearDMR.$O ClearMen.$O ClearPoi.$O  \
	CloseScr.$O CloseWin.$O CloseWor.$O CurrentT.$O DisplayA.$O  \
	DisplayB.$O DisposeO.$O DoubleCl.$O DrawBord.$O DrawIma1.$O  \
	DrawImag.$O EasyRequ.$O EasyReq.$O EndRefre.$O EndReque.$O EraseIma.$O  \
	FreeClas.$O FreeReme.$O FreeScre.$O FreeSysR.$O  \
	GadgetMo.$O GetAttr.$O GetDefPr.$O GetDefau.$O GetPrefs.$O  \
	GetScre1.$O GetScree.$O InitRequ.$O IntuiTex.$O Intuitio.$O  \
	ItemAddr.$O LockIBas.$O LockPub1.$O LockPubS.$O MakeClas.$O  \
	MakeScre.$O ModifyID.$O ModifyPr.$O MoveScre.$O MoveWin1.$O  \
	MoveWind.$O NewModif.$O NewObjec.$O NewObj.$O NextObje.$O NextPubS.$O  \
	ObtainGI.$O OffGadge.$O OffMenu.$O OnGadget.$O OnMenu.$O  \
	OpenIntu.$O OpenScr1.$O OpenScre.$O OpenScrT.$O OpenWin1.$O OpenWind.$O  \
	OpenWinT.$O OpenWork.$O PointInI.$O PrintITe.$O PubScree.$O QueryOve.$O  \
	Refresh1.$O RefreshG.$O RefreshW.$O ReleaseG.$O RemakeDi.$O  \
	RemoveCl.$O RemoveGL.$O RemoveGa.$O ReportMo.$O ReportM1.$O Request.$O  \
	ResetMen.$O RethinkD.$O ScreenT1.$O ScreenTo.$O SetAttrs.$O SetAtt.$O  \
	SetDMReq.$O SetDefau.$O SetEditH.$O SetGadge.$O SetGadAt.$O \
	SetMenuS.$O SetMouse.$O SetPoint.$O SetPrefs.$O SetPubSc.$O  \
	SetWindo.$O ShowTitl.$O SizeWind.$O SysReqHa.$O UnlockIB.$O  \
	UnlockP1.$O UnlockPu.$O ViewAddr.$O ViewPort.$O WBenchT1.$O  \
	WBenchTo.$O WindowLi.$O WindowT1.$O WindowTo.$O ZipWindo.$O  

clib:	$(CLIB)

