CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	AddAnimO.$O AddBob.$O AddFont.$O  \
	AddVSpri.$O AllocRas.$O AndRectR.$O AndRegio.$O Animate.$O  \
	AreaDraw.$O AreaElli.$O AreaEnd.$O AreaMove.$O AskFont.$O  \
	AskSoftS.$O AttemptL.$O BitMapSc.$O BltBitM1.$O BltBitMa.$O  \
	BltClear.$O BltMaskB.$O BltPatte.$O BltTempl.$O CBump.$O  \
	CMove.$O CWait.$O ChangeSp.$O ClearEOL.$O ClearRec.$O  \
	ClearReg.$O ClearScr.$O ClipBlit.$O CloseFon.$O CloseMon.$O  \
	CopySBit.$O DisownBl.$O DisposeR.$O DoCollis.$O Draw.$O  \
	DrawElli.$O DrawGLis.$O EraseRec.$O ExtendFo.$O FindDisp.$O  \
	Flood.$O FontExte.$O FreeColo.$O FreeCopL.$O FreeCprL.$O  \
	FreeGBuf.$O FreeRast.$O FreeSpri.$O FreeVPor.$O GetColor.$O  \
	GetDispl.$O GetGBuff.$O GetRGB4.$O GetSprit.$O GetVPMod.$O  \
	GfxAssoc.$O GfxFree.$O GfxLookU.$O GfxNew.$O InitArea.$O  \
	InitBitM.$O InitGMas.$O InitGels.$O InitMask.$O InitRast.$O  \
	InitTmpR.$O InitVPor.$O InitView.$O LoadRGB4.$O LoadView.$O  \
	LockLaye.$O MakeVPor.$O ModeNotA.$O Move.$O MoveSpri.$O  \
	MrgCop.$O NewRegio.$O NextDisp.$O OpenFont.$O OpenMoni.$O  \
	OrRectRe.$O OrRegion.$O OwnBlitt.$O PolyDraw.$O QBSBlit.$O  \
	QBlit.$O ReadPix1.$O ReadPix2.$O ReadPixe.$O RectFill.$O  \
	RemFont.$O RemIBob.$O RemVSpri.$O ScalerDi.$O ScrollRa.$O  \
	ScrollVP.$O SetAPen.$O SetBPen.$O SetColli.$O \
	SetDrMd.$O SetFont.$O SetRGB4.$O SetRGB4C.$O SetRast.$O  \
	SetSoftS.$O SortGLis.$O StripFon.$O SyncSBit.$O Text.$O  \
	TextExte.$O TextFit.$O TextLeng.$O UCopperL.$O UnlockLa.$O  \
	VBeamPos.$O VideoCon.$O WaitBOVP.$O WaitBlit.$O WaitTOF.$O  \
	WeighTAM.$O WritePi1.$O WritePi2.$O WritePix.$O XorRectR.$O  \
	XorRegio.$O

clib:	$(CLIB)

