CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	BeginUpd.$O BehindLa.$O CreateB1.$O CreateBe.$O CreateU1.$O  \
	CreateUp.$O DeleteLa.$O DisposeL.$O EndUpdat.$O FattenLa.$O  \
	InitLaye.$O InstallC.$O InstallL.$O LockLay1.$O LockLay2.$O  \
	LockLaye.$O MoveLay1.$O MoveLaye.$O MoveSize.$O NewLayer.$O  \
	ScrollLa.$O SizeLaye.$O SwapBits.$O ThinLaye.$O UnlockL1.$O  \
	UnlockL2.$O UnlockLa.$O UpfrontL.$O WhichLay.$O 

clib:	$(CLIB)

