CC=cc
AS=as
CFLAGS=
AFLAGS=
O=oss

.a68.$O:
	$(AS) -o $@ $(AFLAGS) $*.a68

CLIB=\
	AddBootN.$O AddConfi.$O AddDosNo.$O AllocBoa.$O AllocCon.$O  \
	AllocExp.$O ConfigBo.$O ConfigCh.$O FindConf.$O  \
	FreeBoar.$O FreeConf.$O FreeExpa.$O GetCurre.$O MakeDosN.$O  \
	ObtainCo.$O ReadExp1.$O ReadExpa.$O ReleaseC.$O RemConfi.$O  \
	SetCurre.$O WriteExp.$O

clib:	$(CLIB)

